services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      target: development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: debug
